{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    {{- include "k8s-app.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "k8s-app.frontend.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
{{- end }}

