{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    {{- include "k8s-app.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "k8s-app.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-app.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        {{- with .Values.frontend.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}

